version: '3'
services:
  eureka-server:
    image: eureka-server.jar
    ports:
      - "9102:9102"
  ms_gateway:
    image: ms_gateway.jar
    ports:
      - "9103:9103"
    depends_on:
      - eureka-server
  ms_gestionPatient:
    image: ms_gestionPatient.jar
    environment: 
      -SQL_DB_USERNAME=${SQL_DB_USERNAME}
      -SQL_DB_PASSWORD=${SQL_DB_PASSWORD}
      -MS_PATIENT_DB_URL=${MS_PATIENT_DB_URL}
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server
  ms_gestionHistorique:
    image: ms_gestionhistorique.jar
    environment: 
      -NOSQL_DB_USERNAME=${NOSQL_DB_USERNAME}
      -NOSQL_DB_PASSWORD=${NOSQL_DB_PASSWORD}
      -NOSQL_HOST=${NOSQL_HOST}
      -NOSQL_PORT=${NOSQL_PORT}
      -NOSQL_DB_NAME=${NOSQL_DB_NAME}
    ports:
      - "9003:9003"
    depends_on:
      - eureka-server
  ms_gestionrisque:
    image: ms_gestionrisque.jar
    ports:
      - "9004:9004"
    depends_on:
      - eureka-server
  ms_frontend:
    image: ms_frontend.jar
    environment: 
      -TEST_USER_PWD=${TEST_USER_PWD}
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - ms_gateway
