version: '3'
services:
  eureka-server:
    image: eureka-server-image
    ports:
      - "9102:9102"
  ms-gateway:
    image: ms_gateway-image
    ports:
      - "9103:9103"
    depends_on:
      - eureka-server
  ms-gestionpatient:
    image: ms_gestionpatient-image
    environment: 
      - MS_PATIENT_DB_URL=${MS_PATIENT_DB_URL}
      - SQL_DB_USERNAME=${SQL_DB_USERNAME}
      - SQL_DB_PASSWORD=${SQL_DB_PASSWORD}
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server
  ms-gestionhistorique:
    image: ms_gestionhistorique-image
    environment: 
      - NOSQL_DB_USERNAME=${NOSQL_DB_USERNAME}
      - NOSQL_DB_PASSWORD=${NOSQL_DB_PASSWORD}
      - NOSQL_HOST=${NOSQL_HOST}
      - NOSQL_PORT=${NOSQL_PORT}
      - NOSQL_DB_NAME=${NOSQL_DB_NAME}
    ports:
      - "9003:9003"
    depends_on:
      - eureka-server
  ms-gestionrisque:
    image: ms_gestionrisque-image
    ports:
      - "9004:9004"
    depends_on:
      - eureka-server
      - ms-gestionpatient
      - ms-gestionhistorique
  ms-frontend:
    image: ms_frontend-image
    environment: 
      - TEST_USER_PWD=${TEST_USER_PWD}
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - ms-gateway
      - ms-gestionpatient
      - ms-gestionrisque
      - ms-gestionhistorique
    

